import type { Permission } from "./permissions";

/**
 * Per-page atomic permission scopes for the self-confirm gate.
 * On entry to each page, we check if the user has any selfConfirmable
 * permissions in the relevant scope and prompt a one-click activation.
 *
 * Base permissions (scene:view, event:view, etc.) are already always granted
 * and will never surface as selfConfirmable — they can safely be included here.
 */
export const PAGE_PERMISSION_SCOPES = {
  script: new Set<Permission>([
    "script:import",
    "script:manage",
    "script:edit",
    "script:annotate",
    "script:comment",
    "script:create_block",
    "script:delete_block",
    "script:edit_block",
    "script:set_character",
    "script:set_type",
    "script:set_tag",
    "script:reorder",
    "script:mount",
    "script:edit_comment_any",
    "script:delete_comment_any",
    "rehearsal_mark:create",
    "rehearsal_mark:edit",
    "rehearsal_mark:delete",
    "rehearsal_mark:move",
  ]),

  dramaturgy: new Set<Permission>([
    "scene:create",
    "scene:delete",
    "scene:rename",
    "scene:renumber",
    "scene:change_type",
    "scene:edit_synopsis",
    "scene:edit_action_line",
    "scene:edit_music",
    "scene:edit_stage_notes",
    "scene:edit_expected_duration",
    "scene:mount",
    "dramaturgy:import",
    "dramaturgy_view:create",
    "dramaturgy_view:delete",
    "dramaturgy_view:overwrite",
    "dramaturgy_view:create_public",
    "dramaturgy_view:delete_public",
    "dramaturgy_view:overwrite_public",
    "tag_group:create",
    "tag_group:delete",
    "tag_group:rename",
    "tag_group:edit_range_config",
    "tag_group:set_default_option",
    "tag_group:set_lyric_split",
    "tag_group:reorder",
    "tag_option:create",
    "tag_option:delete",
    "tag_option:rename",
    "tag_option:edit_color",
    "tag_option:reorder",
  ]),

  characters: new Set<Permission>([
    "character:create",
    "character:delete",
    "character:rename",
    "character:change_type",
    "character:set_members",
    "character:edit_gender",
    "character:edit_biography",
    "character:edit_role_type",
  ]),

  // Atomic cue_list/cue management permissions. Per-list resource grants
  // (cue_list:edit, cue_list:manage_permissions) are handled separately by CuePage.
  cuelists: new Set<Permission>([
    "cue_list:create",
    "cue_list:delete",
    "cue_list:rename",
    "cue_list:reorder",
    "cue_list:edit_abbr",
    "cue_list:edit_description",
    "cue_list:create_any",
    "cue_list:delete_any",
    "cue_list:rename_any",
    "cue_list:reorder_any",
    "cue_list:edit_abbr_any",
    "cue_list:edit_description_any",
    "cue_list:manage_permissions_any",
    "cue:create",
    "cue:delete",
    "cue:renumber",
    "cue:rename",
    "cue:edit_description",
    "cue:move",
    "cue:mount",
    "cue:comment",
    "cue:create_any",
    "cue:delete_any",
    "cue:renumber_any",
    "cue:rename_any",
    "cue:edit_description_any",
    "cue:move_any",
    "cue:mount_any",
    "cue:edit_comment_any",
    "cue:delete_comment_any",
  ]),

  events: new Set<Permission>([
    "event:create",
    "event:create_tech_req",
    "event:edit_tech_req",
    "event:assign_tech_req",
    "event:delete_tech_req",
    "event:create_tech_req_any",
    "event:edit_tech_req_any",
    "event:assign_tech_req_any",
    "event:delete_tech_req_any",
    "event:view_call_sheet_any",
    "event:view_tech_req",
    "event:view_tech_req_any",
  ]),

  reports: new Set<Permission>([
    "report:create",
    "report:edit",
    "report:publish",
    "report:delete",
    "report:create_note",
    "report:edit_note",
    "report:delete_note",
    "report:create_note_any",
    "report:edit_note_any",
    "report:delete_note_any",
    "report:modify_published",
    "report:revoke",
    "report:reply",
    "report:edit_comment_any",
    "report:delete_comment_any",
    "note:comment",
    "note:edit_comment_any",
    "note:delete_comment_any",
  ]),

  assets: new Set<Permission>([
    "asset:rename",
    "asset:overwrite",
    "asset:change_type",
    "asset:delete",
    "asset:mount",
    "asset:unmount",
    "asset:view_any",
    "asset:delete_any",
    "asset:rename_any",
    "asset:change_type_any",
    "asset:overwrite_any",
    "asset:mount_any",
    "asset:unmount_any",
    "asset:download_any",
    "asset:share_downloadable",
    "asset:share_any",
    "asset:share_any_downloadable",
  ]),
} as const;

export type PageScope = keyof typeof PAGE_PERMISSION_SCOPES;
