ALTER TABLE production ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE production ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE production ADD COLUMN IF NOT EXISTS type TEXT;
ALTER TABLE production ADD COLUMN IF NOT EXISTS type_label TEXT;
ALTER TABLE production ADD COLUMN IF NOT EXISTS language TEXT;
